apiVersion: serverless.pml.com.cn/v1
kind: Quota
metadata:
  labels:
    app.kubernetes.io/name: quota
    app.kubernetes.io/instance: quota-sample
    app.kubernetes.io/part-of: quota
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: quota
  name: quota-sample
spec:
  supervisorName: field1
  localName: cluster1
  networkRegister: {"a":"aa", "b":"bb"}
  childName: [a,b,c]
  childAlert: {"a":True, "b":True}
  clusterAreaType: aaa
  podQpsQuota: {"pod1":10, "pod2":20}
  podQpsReal: {"pod1":9, "pod2":15}
  podQpsIncreaseOrDecrease: {"pod1":1, "pod2":0}

